server:
  port: ${APP_PORT:8080}
spring:
  profiles:
    active: dev  #dev-为开发环境、test-为测试环境、prod-为正式测试环境，上线时请切换,切记！！！
  application:
    name: integration-platform #集成平台
  servlet:
    multipart: # 附件大小限制
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA_NAME:integration-platform}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  redis:
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        max-wait: -1
        min-idle: 5
logging:
  file:
    path: ${APP_LOG_PATH:/data/integration/logs/}
mybatis-plus:
  type-aliases-package: net.jqsoft.integration.platform.model.*
  type-enums-package: net.jqsoft.integration.platform.model.enums #枚举包地址
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
  mapper-locations: classpath:mapper/*.xml
swagger:
  enabled: false
dolphinscheduler:
  enabled: true
  root-uri: http://localhost:12345/
  token: 45f7fec30ea674e417e74619f28b43a7
management:
  endpoint:
    health:
      probes:
        enabled: true
