server:
  port: ${APP_PORT:8081}
spring:
  redis:
    host: 10.1.150.152
    port: 11976
    password: jqkj5350**)
    database: 8
  datasource:
    url: jdbc:mysql://10.1.152.19:3306/dolphinscheduler?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: jqkj5350**)
swagger:
  enabled: true

dataReporting:
  token: 094899029e0111427adec6e27724dc7b
  reportUrl:
