#----------------------     ????     -----------------------
server:
  port: 8081 #??
logging: #??
  file:
    path: /data/integration/logs/ #??????

#----------------------     management??        -----------------------
#??Gateway actuator endpoint??CVE-2022-22947
management:
  endpoint:
    gateway:
      enabled: false


spring:
  profiles:
    active: dev #dev-??????test-??????????????????????,?????
  devtools:
    restart:
      enabled: true #?????
  application:
    name: integration-platform #?????
