spring:
  redis:
    timeout: 6000ms
    host: 10.1.150.152
    port: 11976
    password: jqkj5350**)
    database: 8
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        max-wait: -1
        min-idle: 5
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.152.19:3306/integration-platform?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: jqkj5350**)
    validationQuery: SELECT 1 FROM DUAL
swagger:
  enabled: true