server:
  port: ${APP_PORT:8081}
spring:
  redis:
    host: 10.1.150.150
    port: 47301
    password: redis!@@&
    database: 8
  datasource:
    url: jdbc:mysql://10.1.150.150:30782/dolphinscheduler?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ds
    password: ds
swagger:
  enabled: true
