logging:
  file:
    path: D:\data\integration-platform
mybatis-plus:
  type-aliases-package: net.jqsoft.integration.platform.model.*
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
  mapper-locations: classpath:mapper/*.xml
spring:
  profiles:
    active: dev  #dev-为开发环境、test-为测试环境、prod-为正式测试环境，上线时请切换,切记！！！
  application:
    name: integration-platform #集成平台
  servlet:
    multipart: # 附件大小限制
      max-file-size: 10MB
      max-request-size: 10MB

